# Generated by Django 3.2.5 on 2021-08-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktest',
            name='fuck_django_migrations_are_shit',
        ),
    ]
